### ISSUE TITLE
ubuntu 16.04 rear-2.2-git.0.e425913.unknown.changed breaks automation

### ISSUE THREAD

**Issue by gdha** [gdha/rear-automated-testing#36]
Before (until stable 2.2) we did not got the following prompt:
![virtualbox_recover_ubuntu16_06_11_2017_13_36_10](https://user-images.githubusercontent.com/888633/32441511-4b817e74-c2f8-11e7-8bc2-bbf62ce9b8bb.png)

Need to verify @jsmeix updates/changes regarding automated input. Need more stuff in the local.conf file I guess

**Comment by gdha** [comment]
We can fix this in script `/usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh`
by adding before line `if ! test $MANUAL_MAC_MAPPING ; then` some extra lines of code:
````
if unattended_recovery ; then
    # we gonna cheat a bit and say we have map made (but we did not and just hope that the interfaces
    # will be in the same order on the recover vm as on the client vm)
    MANUAL_MAC_MAPPING=true
fi
````

**Comment by jsmeix** [comment]
That dialog is on my personal to-do list to get
https://github.com/rear/rear/issues/1399
implemented.

Next week is again a SUSE Hack Week
cf. https://hackweek.suse.com/
where I will primarily work on getting
https://github.com/rear/rear/issues/1399
sufficiently done.

FYI:
I get this dialog about "network device" [sic!] (there is
no such thing as a network 'device' in Linux because
there is no device node file for a network 'interface',
I will also fix the wording when I use UserInput there)
all the time in its basically useless form when only
one single new network interface is there like
<pre>
The original network device ... is not available.
Please select another device:
1) eth0 12:34:56:78:90:AB
2) Skip replacing the network device
</pre>
where an automated selection of the single existing
new network interface is the only reasonable default action.

**Comment by jsmeix** [comment]
@gdha 
independent of what I will do via
https://github.com/rear/rear/issues/1399
I think your "extra lines of code" in your
https://github.com/gdha/rear-automated-testing/issues/36#issuecomment-342550639
are needed in any case because when the user has explicitly
specified an "unattended_recovery" then not any kind of
user dialog must ever show up.

An offhanded idea for "ReaR future":

When the user has explicitly specified an "unattended_recovery"
then even not any user dialog of any program that is called
by ReaR must ever show up by default.

But in practice it is impossible to foresee all cases
under what special circumstances arbitrary programs
may show a user dialog - in particular things like
a user confirmation "yes/no" dialog.

Perhaps as a generic way how to avoid "yes/no" dialogs
in case of 'unattended_recovery' is to redirect STDIN
to the output of /usr/bin/yes like
<pre>
exec 0< <( yes )
</pre>

Then all programs that unexpectedly read input
get (an unlimited number of) 'y' as input.

This should not conflict with programs that need to get
input explicitly from the user (from the user's terminal)
like third-party backup restore tools that cannot run unattended.
Programs that need input explicitly from the user
should be called in ReaR as
<pre>
PROGRAM ... 0<&6 1>&7 2>&8
</pre>
cf. "What to do with stdout and stderr" at
https://github.com/rear/rear/wiki/Coding-Style

Examples on command line:
<pre>
# ( exec 6<&0 ; exec 0< <( yes ) ; head -n 3 | cat -n ; read -p 'enter something: ' input 0<&6 ; echo "got '$input'" )
     1  y
     2  y
     3  y
enter something: Hello World
got 'Hello World'

# ( exec 6<&0 ; exec 0< <( yes ) ; touch qqq ; rm -vi qqq ; read -p 'enter something: ' input 0<&6 ; echo "got '$input'" )
rm: remove regular empty file `qqq'? removed `qqq'
enter something: Hello World
got 'Hello World'
</pre>

**Comment by jsmeix** [comment]
An addon or side note to my above
https://github.com/gdha/rear-automated-testing/issues/36#issuecomment-342769055
redirect STDIN to the output of /usr/bin/yes via
<pre>
exec 0< <( yes )
</pre>

This results unlimited fast 'y' input which could result
in a tight loop during "rear recover" when a program
does no like 'y' as input (e.g. it may only accept 'yes')
so that it repeats endlessly and asks again and again
the same question like "enter 'yes' or 'no'".

It might be perhaps better to redirect STDIN to manually
implemented slow input e.g. only one 'y' per second like
<pre>
exec 0< <( while true ; do echo 'y' ; sleep 1 ; done )
</pre>
to avoid possible endlessly running tight loops.

Or perhaps even trying several positive input values like
<pre>
exec 0< <( while true ; do echo 'y' ; sleep 1 ; echo 'yes' ; sleep 1 ; done )
</pre>

**Comment by jsmeix** [comment]
Now I know the example where a program shows a "yes/no" dialog
but only accepts 'yes' (but not 'y'):
<pre>
# ssh root@remote_host
The authenticity of host ... can't be established.
RSA key fingerprint is ...
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no':
</pre>
But ssh does not read its input from STDIN
(ssh reads directly from the user's terminal)
so that in this case no STDIN redirection helps.

**Comment by gdha** [comment]
On **libvirt** it works fine as well.
