### ISSUE TITLE
I am having issue when i try to restore the rear backup associated with sles15sp1

### ISSUE THREAD

**Issue by mantriharis** [gdha/rear-automated-testing#84]
# rear recover
Relax-and-Recover 2.4 / Git
Running rear recover (PID 4771)
Using log file: /var/log/rear/rear-hedcb019.log
Running workflow recover within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
Started rpc.statd.
RPC status rpc.statd available.
Using backup archive '/tmp/rear.fak44YuJUkLaujC/outputfs/hedcb019/backup.tar.gz'
Will do driver migration (recreating initramfs/initrd)
Calculating backup archive size
Backup archive size is 1.1G     /tmp/rear.fak44YuJUkLaujC/outputfs/hedcb019/backup.tar.gz (compressed)
Switching to manual disk layout configuration (/etc/rear/disklayout.conf exists)
Setting up multipathing
Activating multipath
multipath activated
Starting multipath daemon
multipathd started
Listing multipath device found
mpatha (36005076304ffd70e000000000000f405) dm-0 IBM,2107900 size=50G
Enforced manual disk layout configuration (MIGRATION_MODE is 'true')
Using /dev/mapper/mpatha (same name and same size) for recreating /dev/mapper/mpatha
Current disk mapping table (source => target):
  /dev/mapper/mpatha => /dev/mapper/mpatha

Confirm or edit the disk mapping
1) Confirm disk mapping and continue 'rear recover'
2) Confirm identical disk mapping and proceed without manual configuration
3) Edit disk mapping (/var/lib/rear/layout/disk_mappings)
4) Use Relax-and-Recover shell and return back to here
5) Abort 'rear recover'
(default '1' timeout 300 seconds)
1
User confirmed disk mapping
Confirm or edit the disk layout file
1) Confirm disk layout and continue 'rear recover'
2) Edit disk layout (/var/lib/rear/layout/disklayout.conf)
3) View disk layout (/var/lib/rear/layout/disklayout.conf)
4) View original disk space usage (/var/lib/rear/layout/config/df.txt)
5) Use Relax-and-Recover shell and return back to here
6) Abort 'rear recover'
(default '1' timeout 300 seconds)
1
User confirmed disk layout file
Doing SLES12-SP1 (and later) btrfs subvolumes setup because the default subvolume path contains '@/.snapshots/'
btrfsdefaultsubvol entry with empty subvolume_path for /dev/mapper/rootvg-expvol at /exploit may indicate an error, skipping default subvolume setup for it.
btrfsdefaultsubvol entry with empty subvolume_path for /dev/mapper/rootvg-homevol at /home may indicate an error, skipping default subvolume setup for it.
btrfsdefaultsubvol entry with empty subvolume_path for /dev/mapper/rootvg-iemvol at /var/opt/BESClient may indicate an error, skipping default subvolume setup for it.
btrfsdefaultsubvol entry with empty subvolume_path for /dev/mapper/rootvg-optvol at /opt may indicate an error, skipping default subvolume setup for it.
btrfsdefaultsubvol entry with empty subvolume_path for /dev/mapper/rootvg-varlogvol at /var/log may indicate an error, skipping default subvolume setup for it.
Confirm or edit the disk recreation script
1) Confirm disk recreation script and continue 'rear recover'
2) Edit disk recreation script (/var/lib/rear/layout/diskrestore.sh)
3) View disk recreation script (/var/lib/rear/layout/diskrestore.sh)
4) View original disk space usage (/var/lib/rear/layout/config/df.txt)
5) Use Relax-and-Recover shell and return back to here
6) Abort 'rear recover'
(default '1' timeout 300 seconds)
1
User confirmed disk recreation script
Start system layout restoration.
Creating partitions for disk /dev/mapper/mpatha (msdos)
Creating LVM PV /dev/mapper/mpatha-part2
Creating LVM VG 'rootvg'; Warning: some properties may not be preserved...
Creating LVM volume 'rootvg/expvol'; Warning: some properties may not be preserved...
Creating LVM volume 'rootvg/homevol'; Warning: some properties may not be preserved...
Creating LVM volume 'rootvg/iemvol'; Warning: some properties may not be preserved...
Creating LVM volume 'rootvg/optvol'; Warning: some properties may not be preserved...
Creating LVM volume 'rootvg/rootvol'; Warning: some properties may not be preserved...
Creating LVM volume 'rootvg/swapvol'; Warning: some properties may not be preserved...
Creating LVM volume 'rootvg/varlogvol'; Warning: some properties may not be preserved...
Creating filesystem of type btrfs with mount point / on /dev/mapper/rootvg-rootvol.
Mounting filesystem /
/usr/lib/snapper/installation-helper not executable may indicate an error with btrfs default subvolume setup for @/.snapshots/1/snapshot on /dev/mapper/rootvg-rootvol
The disk layout recreation script failed
1) Rerun disk recreation script (/var/lib/rear/layout/diskrestore.sh)
2) View 'rear recover' log file (/var/log/rear/rear-hedcb019.log)
3) Edit disk recreation script (/var/lib/rear/layout/diskrestore.sh)
4) View original disk space usage (/var/lib/rear/layout/config/df.txt)
5) Use Relax-and-Recover shell and return back to here
6) Abort 'rear recover'
(default '1' timeout 300 seconds)

**Comment by mantriharis** [comment]
When i try to restore i  get the below error ...
Mounting filesystem /
/usr/lib/snapper/installation-helper not executable may indicate an error with btrfs default subvolume setup for @/.snapshots/1/snapshot on /dev/mapper/rootvg-rootvol
The disk layout recreation script failed

**Comment by mantriharis** [comment]
errorlog details

+++ mkdir -p /mnt/local/.snapshots
+++ mount -t btrfs -o rw,relatime,ssd,space_cache -o subvol=@/.snapshots /dev/mapper/rootvg-rootvol /mnt/local/.snapshots
mount: /mnt/local/.snapshots: wrong fs type, bad option, bad superblock on /dev/mapper/rootvg-rootvol, missing codepage or helper program, or other error.

**Comment by jsmeix** [comment]
@mantriharis 
when you like to report a ReaR issue to ReaR upstream this is not the right place.

The right place to report a ReaR issue to ReaR upstream is
https://github.com/rear/rear/issues

When you click on the `[New issue]` button at
https://github.com/rear/rear/issues
you see this
https://raw.githubusercontent.com/rear/rear/master/.github/ISSUE_TEMPLATE.md
which describes how to submit issues so that we (i.e. the ReaR upstream
free software developers) have at least a chance to understand
what goes on on your particular system with your particular hardware
in your particular environment which is a precondition to be able to help you.

In particular for what is needed by us to analyze and debug a "rear recover" failure
I added an itemization that is about
`To analyze and debug a "rear recover" failure the following information is mandatory`
to the "Debugging issues with Relax-and-Recover" section in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
@mantriharis 
when you get `/usr/lib/snapper/installation-helper not executable`
I guess the reason is that you use SLES with btrfs
but your etc/rear/local.conf file is not based on the right template in
usr/share/rear/conf/examples/
i.e. your etc/rear/local.conf file is not based on one of
```
usr/share/rear/conf/examples/SLE12-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf
```
When you use SLES12-SP2 or later the right template is
```
usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf
```
which is currently at ReaR upstream this one
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf

**Comment by gdha** [comment]
@mantriharis this is indeed a support question towards ReaR and not meant for this project - therefore, the 'invalid' label. However, thank you for reporting the issue to the right channel - https://github.com/rear/rear/issues/2584

**Comment by mantriharish** [comment]
actually gratien,,support is unabelto figure out this issue since sles15sp2 is new on power and i am running from door to door to get the resolution so i have come to this for help and some inputs,,not sure wether this is a bug or something else,,the same rear works fine when the system is on sles12 and not sles15 ,i infact made changes to the rear packages as well and considered the laters from repo associated with sles15 and also form the relax and recover link and the error reamins the same



Mounting filesystem /
/usr/lib/snapper/installation-helper not executable may indicate an error with btrfs default subvolume setup for @/.snapshots/1/snapshot on /dev/mapper/rootvg-rootvol
The disk layout recreation script failed
1) Rerun disk recreation script (/var/lib/rear/layout/diskrestore.sh)
2) View 'rear recover' log file (/var/log/rear/rear-hedcb019.log)
3) Edit disk recreation script (/var/lib/rear/layout/diskrestore.sh)
4) View original disk space usage (/var/lib/rear/layout/config/df.txt)
5) Use Relax-and-Recover shell and return back to here
6) Abort 'rear recover'
(default '1' timeout 300 seconds)

**Comment by mantriharish** [comment]
@jsmeix :Thanks for your comments...

I did try to your inputs like the below...as per the below link
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf

i have take the data from the file above and populated the same in the below path and file that i already have on the server
hedcb019:/usr/share/rear/conf/examples # ls -ltr
total 768
-rw-r--r-- 1 root root  573 Aug 10  2018 rescue-and-backup-on-same-ISO-image-example.conf
-rw-r--r-- 1 root root  923 Aug 10  2018 borg-example.conf
-rw-r--r-- 1 root root  755 Aug 10  2018 USB-and-Samba-example.conf
-rw-r--r-- 1 root root 2764 Aug 10  2018 SLE12-btrfs-example.conf
-rw-r--r-- 1 root root 4374 Aug 10  2018 SLE12-SP1-btrfs-example.conf
-rw-r--r-- 1 root root 1479 Aug 10  2018 SLE11-ext3-example.conf
-rw-r--r-- 1 root root 2777 Aug 10  2018 SLE11-SLE12-SAP-HANA-UEFI-example.conf
-rw-r--r-- 1 root root 1597 Aug 10  2018 RHEL7-PPC64LE-Mulitpath-PXE-GRUB.conf
-rw-r--r-- 1 root root 2864 Aug 10  2018 RHEL7-ISO-Oracle-example.conf
-rw-r--r-- 1 root root  865 Aug 10  2018 RHEL6-NETFS-of-NBU-master-example.conf
-rw-r--r-- 1 root root 1013 Aug 10  2018 PXE-booting-example-with-URL-style.conf
-rw-r--r-- 1 root root 5019 Mar  9 07:27 SLE12-SP2-btrfs-example.conf----------------------this is the one i populated with the data

hedcb019:/usr/share/rear/conf/examples # cat SLE12-SP2-btrfs-example.conf
# Begin example setup for SLE12-SP2 with default btrfs subvolumes.
# Since SLE12-SP1 what is mounted at '/' is a btrfs snapshot subvolume
# see https://github.com/rear/rear/issues/556
# and since SLE12-SP2 btrfs quota via "snapper setup-quota" is needed
# see https://github.com/rear/rear/issues/999
# You must adapt "your.NFS.server.IP/path/to/your/rear/backup" at BACKUP_URL.
# You must decide whether or not you want to have /home/* in the backup.
# It depends on the size of your harddisk whether or not /home is by default
# a btrfs subvolume or a separated xfs filesystem on a separated partition.
# You may activate SSH_ROOT_PASSWORD and adapt the 'password_on_the_rear_recovery_system'.
# For basic information see the SLE12-SP2 manuals.
# Also see the support database article "SDB:Disaster Recovery"
# at http://en.opensuse.org/SDB:Disaster_Recovery
# In particular note:
# There is no such thing as a disaster recovery solution that "just works".
# Regarding btrfs snapshots:
# Recovery of btrfs snapshot subvolumes is not possible.
# Only recovery of "normal" btrfs subvolumes is possible.
# On SLE12-SP1 and SP2 the only exception is the btrfs snapshot subvolume
# that is mounted at '/' but that one is not recreated but instead
# it is created anew from scratch during the recovery installation with the
# default first btrfs snapper snapshot subvolume path "@/.snapshots/1/snapshot"
# by the SUSE tool "installation-helper --step 1" (cf. below).
# Other snapshots like "@/.snapshots/234/snapshot" are not recreated.
# Create ReaR recovery system as ISO image:
OUTPUT=ISO
# Store the backup file via NFS on a NFS server:
BACKUP=NETFS
# BACKUP_OPTIONS variable contains the NFS mount options and
# with 'mount -o nolock' no rpc.statd (plus rpcbind) are needed:
BACKUP_OPTIONS="nfsvers=3,nolock"
# If the NFS server is not an IP address but a hostname,
# DNS must work in the ReaR recovery system when the backup is restored.
BACKUP_URL=nfs://your.NFS.server.IP/path/to/your/rear/backup
# Keep an older copy of the backup in a HOSTNAME.old directory
# provided there is no '.lockfile' in the HOSTNAME directory:
NETFS_KEEP_OLD_BACKUP_COPY=yes
# Have all modules of the original system in the recovery system with the
# same module loading ordering as in the original system by using the output of
#   lsmod | tail -n +2 | cut -d ' ' -f 1 | tac | tr -s '[:space:]' ' '
# as value for MODULES_LOAD (cf. https://github.com/rear/rear/issues/626):
#MODULES_LOAD=( )
# On SLE12-SP1 and SP2 with default btrfs subvolumes what is mounted at '/' is a btrfs snapshot subvolume
# that is controlled by snapper so that snapper is needed in the recovery system.
# In SLE12-SP1 and SP2 some btrfs subvolume directories (/var/lib/pgsql /var/lib/libvirt/images /var/lib/mariadb)
# have the "no copy on write (C)" file attribute set so that chattr is required in the recovery system
# and accordingly also lsattr is useful to have in the recovery system (but not strictly required):
REQUIRED_PROGS+=( snapper chattr )
PROGS+=( lsattr )
# Snapper setup by the recovery system uses /usr/lib/snapper/installation-helper
# that is linked to all libraries where snapper is linked to
# (except libdbus that is only needed by snapper).
# "installation-helper --step 1" creates a snapper config based on /etc/snapper/config-templates/default
COPY_AS_IS+=( /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default )
# Files in btrfs subvolumes are excluded by 'tar --one-file-system'
# so that such files must be explicitly included to be in the backup.
# Files in the following SLE12-SP2 default btrfs subvolumes are
# in the below example not included to be in the backup
#   /.snapshots  /var/crash
# but files in /home are included to be in the backup.
# You may use a command like
#   findmnt -n -r -o TARGET -t btrfs | grep -v '^/$' | egrep -v 'snapshots|crash'
# to generate the values:
BACKUP_PROG_INCLUDE=( /var/cache /var/lib/mailman /var/tmp /var/lib/pgsql /usr/local /opt /var/lib/libvirt/images /boot/grub2/i386-pc /var/opt /srv /boot/grub2/x86_64-efi /var/lib/mariadb /var/spool /var/lib/mysql /tmp /home /var/log /var/lib/named /var/lib/machines )
# The following POST_RECOVERY_SCRIPT implements during "rear recover"
# btrfs quota setup for snapper if that is used in the original system:
POST_RECOVERY_SCRIPT=( 'if snapper --no-dbus -r $TARGET_FS_ROOT get-config | grep -q "^QGROUP.*[0-9]/[0-9]" ; then snapper --no-dbus -r $TARGET_FS_ROOT set-config QGROUP= ; snapper --no-dbus -r $TARGET_FS_ROOT setup-quota && echo snapper setup-quota done || echo snapper setup-quota failed ; else echo snapper setup-quota not used ; fi' )
# This option defines a root password to allow SSH connection
# whithout a public/private key pair
#SSH_ROOT_PASSWORD='password_on_the_rear_recovery_system'
# Let the ReaR recovery system run dhclient to get an IP address
# instead of using the same IP address as the original system:
#USE_DHCLIENT="yes"
# End example setup for SLE12-SP2 with default btrfs subvolumes.

______________________________________________________________________________________________


now i took the rear backup again of the server ,,but unfortunately the issue still persists i get the same old error again

Mounting filesystem /
/usr/lib/snapper/installation-helper not executable may indicate an error with btrfs default subvolume setup for @/.snapshots/1/snapshot on /dev/mapper/rootvg-rootvol
The disk layout recreation script failed
1) Rerun disk recreation script (/var/lib/rear/layout/diskrestore.sh)
2) View 'rear recover' log file (/var/log/rear/rear-hedcb019.log)
3) Edit disk recreation script (/var/lib/rear/layout/diskrestore.sh)
4) View original disk space usage (/var/lib/rear/layout/config/df.txt)
5) Use Relax-and-Recover shell and return back to here
6) Abort 'rear recover'
(default '1' timeout 300 seconds)
Rerunning disk recreation script by default


Please let me know if i made any miss understanding your inputs for the same

**Comment by mantriharish** [comment]
@jsmeix :+1: 

 # cat /etc/rear/local.conf
# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is.
# Our packages will never ship with a site.conf.
hedcb019:~ # cd /usr/share/rear/conf/examples/
hedcb019:/usr/share/rear/conf/examples # ls -ltr
total 768
-rw-r--r-- 1 root root  573 Aug 10  2018 rescue-and-backup-on-same-ISO-image-example.conf
-rw-r--r-- 1 root root  923 Aug 10  2018 borg-example.conf
-rw-r--r-- 1 root root  755 Aug 10  2018 USB-and-Samba-example.conf
-rw-r--r-- 1 root root 2764 Aug 10  2018 SLE12-btrfs-example.conf
-rw-r--r-- 1 root root 4374 Aug 10  2018 SLE12-SP1-btrfs-example.conf
-rw-r--r-- 1 root root 1479 Aug 10  2018 SLE11-ext3-example.conf
-rw-r--r-- 1 root root 2777 Aug 10  2018 SLE11-SLE12-SAP-HANA-UEFI-example.conf
-rw-r--r-- 1 root root 1597 Aug 10  2018 RHEL7-PPC64LE-Mulitpath-PXE-GRUB.conf
-rw-r--r-- 1 root root 2864 Aug 10  2018 RHEL7-ISO-Oracle-example.conf
-rw-r--r-- 1 root root  865 Aug 10  2018 RHEL6-NETFS-of-NBU-master-example.conf
-rw-r--r-- 1 root root 1013 Aug 10  2018 PXE-booting-example-with-URL-style.conf
-rw-r--r-- 1 root root 5019 Mar  9 07:27 SLE12-SP2-btrfs-example.conf

**Comment by mantriharish** [comment]
@jsmeix can you please have a check and let me know what is that is going on i am not able to make any progress further on this issue

**Comment by jsmeix** [comment]
@mantriharish 
this issue here is not the right one (see above) so I won't continue here
instead I continue (only) at https://github.com/rear/rear/issues/2584

**Comment by jsmeix** [comment]
@gdha 
could you close this issue?
(I cannot - I have no rights here)
